settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: app
  path: .
  commands:
    install:
      status: true
      method: go build -gcflags -o /go/app/api
    generate:
      status: true
    run:
      status: true
      method: /go/bin/dlv
  args:
    - exec
    - ./api
    - --headless
    - --listen=:2345
    - --api-version=2
    - --accept-multiclient
  watcher:
    extensions:
    - go
    paths:
    - /
    ignore:
      paths:
      - .git
      - .realize
      - vendor
