version: '3.7'
services:
  app:
    build:
      context: .
      target: build
    volumes:
      - ./:/go/app
    command: realize start
    ports:
      - 1323:1323
      - 2345:2345
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    networks:
      - backend
    depends_on:
      - db
  db:
    build:
      context: ./docker/mysql
    container_name: twitter_clone_db
    volumes:
      - db_data:/var/lib/mysql:cached
    command: [
      '--default-authentication-plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--skip-character-set-client-handshake',
      '--collation-server=utf8mb4_general_ci',
      '--slow-query-log=1',
      '--long-query-time=1',
      '--slow-query-log-file=/var/log/mysql/slow.log',
      '--log-queries-not-using-indexes=0',
      '--log-timestamps=SYSTEM'
    ]
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: twitter_clone
      MYSQL_USER: twitter_clone
      MYSQL_PASSWORD: twitter_clone_password
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
