[mysql]
  dbname  = "twitter_clone"
  host    = "db"
  port    = 3306
  user    = "twitter_clone"
  pass    = "twitter_clone_password"
  sslmode = "false"

[aliases.tables.follows.relationships]
fk_followers_users = {local = "Followers", foreign = "Follower"}
fk_followees_users = {local = "Followees", foreign = "Followee"}
