// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Follows        string
	GooseDBVersion string
	Likes          string
	Tweets         string
	Users          string
}{
	Follows:        "follows",
	GooseDBVersion: "goose_db_version",
	Likes:          "likes",
	Tweets:         "tweets",
	Users:          "users",
}
